### ISSUE TITLE
Preparation of the publication of an accepted manuscript (template Issue)

### ISSUE THREAD

**Issue by jchiquet** [computorg/published-paper-tsne#5]
## Phase 1: acceptance [authors + AE]

When the Associate Editor (AE) is satisfied with the author's answers to the reviewers comments, he/she exchanges with authors  that (via the discussion tool on OpenReview)

- [x] authors are informed of final acceptance 
- [ ] affiliation, author-url, affiliation-url and other metadata are correctly filled in on the author git repository
- [ ] the manuscript is formatted using the latest Computo extension
- [ ] CI/github-action validates the reproducibility of the manuscript

The authors inform the AE upon completion of the tasks required on their side.
 
## Phase 2: production start-up [AE]

- [ ] the AE asks the editor in chief (EiC) for a DOI for this publication
- [x] the AE invites the corresponding author as a collaborator of computorg: https://github.com/orgs/computorg/people
- [ ] the AE asks the corresponding author to transfer the ownership of their repo to computorg: at the bottom of https://github.com/corresp-author/repo-name/settings, click  "Transfer ownership" and choose "computorg" in "Select one of my organizations"
- [ ] the AE renames this repo to `published-yearmonth-first_author_last_name-manuscript_keyword`, with CC-by 4 licence (year-month in format YYYYMM; use only hyphens, e.g. `published-202407-legrand-wildfires`) and ensures that the repo is public (will appear "in the pipeline"  on the web site if `draft: true`
- [ ] the AE makes an Issue asking for final proofreading by the authors (possibly with some minor additional questions), made as a pull-request on Computorg's repository
- [ ] the AE, assisted by the technical team, ensure that CI works ~~(make sure that gh-pages is enabled for the repo ; that there exists a `gh-pages` branches)~~ **we now use github-actions to push the pages**
- [ ] the AE makes the review public by creating an issue in the repository with a link to the reviews (OR or PCI), [following this model](https://github.com/computorg/published-202509-boulet-simulator/issues/5), and adds the label "review" to this issue (which will automatically link to the review badge in the HTML version of the paper)
- [ ] the AE asks each reviewer by email whether they agree to lift their anonymity; if so, the AE adds this info to the review issue
- [ ] the AE completes the README.md according to [this template](https://github.com/computorg/published-paper-tsne/blob/main/README.md), with appropriate badges
- [ ] the AE archives the repository on [software heritage](https://archive.softwareheritage.org/save/)
- [ ] the AE informs the EiC that phase 2 has ended(check that proofread Issue is closed)

## Phase 3: final publication [EiC]

- [ ] the EiC sets the metadata appropriately (draft: false, repos, doi, google-scholar: true; date: publication date under format MM-DD-YYYY; date-modified: last-modified.)
- [ ] the EiC creates a release of the firstly published version, tagged v1.0, on GitHub `git tag v1.0 -a -s -m "Publication v1.0"`
~~- [ ] the AE adds [an item to the website news](https://computo.sfds.asso.fr/) announcing the publication of a new article~~ now automatically done
~~- [ ] the EiC moves the BibTeX entry from file "in production" to "published" on Computo website, by completing if needed~~ now automatically done
- [ ] the EiC asks the CM to communicate about the new publication is made
